### ISSUE TITLE
When inserting into a table that has more elements than the original table, there are too many ? in the values part of the insert

### ISSUE THREAD

**Issue by poser55** [poser55/linked-db-rows#1]
E.g.

insert into mytable (a,b,c) values (?,?,?,?) 

The issue is then logged as (here with a larger statement):

<#e8e7d0f9> o.p.u.PSQLException: No value specified for parameter 70.
	at o.p.c.v.SimpleParameterList.checkAllParametersSet(SimpleParameterList.java:264)
	at o.p.c.v.QueryExecutorImpl.execute(QueryExecutorImpl.java:293)
	at o.p.jdbc.PgStatement.executeInternal(PgStatement.java:446)
	at o.p.jdbc.PgStatement.execute(PgStatement.java:370)
	at o.p.j.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:149)
	at o.p.j.PgPreparedStatement.executeUpdate(PgPreparedStatement.java:124)
	at c.z.h.p.ProxyPreparedStatement.executeUpdate(ProxyPreparedStatement.java:61)
	at c.z.h.p.HikariProxyPreparedStatement.executeUpdate(HikariProxyPreparedStatement.java)
	at j.i.r.GeneratedMethodAccessor890.invoke(Unknown Source)
	at j.i.r.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at j.l.reflect.Method.invoke(Unknown Source)
	at n.b.j.JdbcWrapper.doExecute(JdbcWrapper.java:422)
	at n.b.j.JdbcWrapper$StatementInvocationHandler.invoke(JdbcWrapper.java:142)
	at n.b.j.JdbcWrapper$DelegatingInvocationHandler.invoke(JdbcWrapper.java:300)
	at c.s.proxy.$Proxy123.executeUpdate(Unknown Source)
	at o.o.t.j.DbImporter.insertOneRecord(DbImporter.java:339)
	at o.o.t.j.DbImporter.lambda$insertRecords$4(DbImporter.java:250)

**Comment by poser55** [comment]
Fixed with commit https://github.com/poser55/linked-db-rows/commit/5cf308b8e5eaf3c28162ac5e9e4f2c4c08dc9472
